[default]
SECRET_KEY = "(ключ проекта)"
SU_name = "(логин админа)"
SU_email = "(почта админа)"
SU_password = "(пароль админа)"
SU_age = "YYYY-MM-DD"
SOCIAL_AUTH_VK_OAUTH2_KEY = ""
SOCIAL_AUTH_VK_OAUTH2_SECRET = ""
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = ""
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = ""
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
SOCIAL_AUTH_GITHUB_KEY = ""
SOCIAL_AUTH_GITHUB_SECRET = ""
DATABASES__default__USER = "логин к БД"
DATABASES__default__PASSWORD = "пароль к БД"
DATABASES__default__NAME = "название файла БД"


[development]


[productions]
SECRET_KEY = "(ключ проекта)"
